clone_depth: 1

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
    ANSI_COLORS: ON
    PLATFORM: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-msvc2015
    CONFIGURATION: Debug
  - TARGET: desktop
    COMPILER: msvc
    ANSI_COLORS: ON
    PLATFORM: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-msvc2017
    CONFIGURATION: Debug
  # Build the 32bit and non-ANSI as Release, one on 2015 and one on 2017, so we
  # catch things that are not a problem on either with 64bit and Debug.
  - TARGET: desktop
    COMPILER: msvc
    ANSI_COLORS: ON
    PLATFORM:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-32b-msvc2015
    CONFIGURATION: Release
  - TARGET: desktop
    COMPILER: msvc
    ANSI_COLORS: OFF
    PLATFORM: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-noansi-msvc2017
    CONFIGURATION: Release
  - TARGET: desktop
    COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-mingw
  - TARGET: rt
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-rt-msvc2015
  - TARGET: rt
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-rt-msvc2017

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/tools/ninja;%PATH%
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" pip install codecov

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat
